steps:
    - name: gcr.io/cloud-builders/docker
      args: ['build', '-t', 'gcr.io/$PROJECT_ID/hello-cloud-run:latest', '.']
    - name: 'gcr.io/cloud-builders/docker'
      args: ["push", "gcr.io/$PROJECT_ID/hello-cloud-run"]